# Generated by Django 4.0rc1 on 2021-12-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_rename_tournament_championship_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_dna_notnull',
        ),
        migrations.RemoveField(
            model_name='raceentry',
            name='full_time',
        ),
        migrations.AlterField(
            model_name='race',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='leaderboard.championship'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.CheckConstraint(check=models.Q(('dna', True), models.Q(('best_lap_time__isnull', False), ('dnf__isnull', False), ('finish_position__isnull', False), ('grid_penalty__isnull', False), ('pit_stops__isnull', False), ('qualifying_position__isnull', False)), _connector='OR'), name='raceentry_dna_notnull'),
        ),
    ]
