# Generated by Django 4.0rc1 on 2021-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_dna_notnull',
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.CheckConstraint(check=models.Q(('dna', True), ('qualifying_position__isnull', False), _connector='OR'), name='raceentry_dna_notnull'),
        ),
    ]
