# Generated by Django 4.0rc1 on 2021-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_raceentry_raceentry_dna_notnull_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_dna_notnull',
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.CheckConstraint(check=models.Q(('dna', True), models.Q(('best_lap_time__isnull', False), ('dnf__isnull', False), ('finish_position__isnull', False), ('full_time__isnull', False), ('grid_penalty__isnull', False), ('pit_stops__isnull', False), ('qualifying_position__isnull', False)), _connector='OR'), name='raceentry_dna_notnull'),
        ),
    ]
