# Generated by Django 4.0rc1 on 2021-12-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_raceentry_raceentry_dna_notnull_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='Championship',
        ),
        migrations.RemoveConstraint(
            model_name='race',
            name='race_unique_tournament_order',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='tournament',
            new_name='championship',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='tournament_order',
            new_name='championship_order',
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_entries', to='leaderboard.race'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('championship_order', 'championship'), name='race_unique_championship_order'),
        ),
    ]
