# Generated by Django 4.0 on 2021-12-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_championship_options_championship_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
