# Generated by Django 4.0 on 2021-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_alter_race_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='race',
            name='schedule_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
