# Generated by Django 4.0 on 2021-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_race_detail_image_race_schedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='length',
            field=models.CharField(choices=[('F', 'Full Race (100%)'), ('L', 'Long Race (50%)'), ('M', 'Medium Race (25%)'), ('S', 'Short Race (5 laps)')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='full_laps',
            field=models.IntegerField(default=60, verbose_name='Laps in a full race (100%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='long_laps',
            field=models.IntegerField(default=30, verbose_name='Laps in a long race (50%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='medium_laps',
            field=models.IntegerField(default=15, verbose_name='Laps in a mediun race (25%)'),
            preserve_default=False,
        ),
    ]
