# Generated by Django 4.0 on 2021-12-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0015_alter_track_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='image',
            new_name='overview_image',
        ),
    ]
