# Generated by Django 4.0 on 2021-12-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0017_track_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='races', to='leaderboard.track'),
        ),
    ]
