# Generated by Django 4.0 on 2021-12-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_raceentry_tires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='race',
            name='schedule_image',
        ),
    ]
