# Generated by Django 4.0 on 2021-12-25 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0022_remove_race_detail_image_remove_race_schedule_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_dna_notnull',
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='best_lap_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='dnf',
            field=models.BooleanField(default=False, verbose_name='Did Not Finish'),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='finish_position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='pit_stops',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='qualifying_position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qualifying Position'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bot', True), ('driver__isnull', True), ('team__isnull', True)), models.Q(('bot', False), ('driver__isnull', False), ('team__isnull', False)), _connector='OR'), name='raceentry_dna_notnull'),
        ),
    ]
