# Generated by Django 4.0 on 2021-12-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0023_remove_raceentry_raceentry_dna_notnull_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'qualifying_position'), name='raceentry_unique_driver_qualifying_position'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'finish_position'), name='raceentry_unique_driver_finish_position'),
        ),
    ]
