# Generated by Django 4.0 on 2021-12-25 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0024_raceentry_raceentry_unique_driver_qualifying_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='grid_penalty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='pit_stops',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
