# Generated by Django 4.0 on 2021-12-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0025_alter_raceentry_grid_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='drivers',
            field=models.ManyToManyField(to='leaderboard.Driver'),
        ),
    ]
