# Generated by Django 4.0 on 2021-12-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0027_rulechapter_ruleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulechapter',
            name='name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
