# Generated by Django 4.0 on 2021-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0028_rulechapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='leaderboard.Driver'),
        ),
    ]
