# Generated by Django 4.0 on 2021-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0029_alter_championship_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentry',
            name='best_lap_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
