# Generated by Django 4.0 on 2021-12-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0031_alter_raceentry_qualifying_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'get_latest_by': 'start_date', 'ordering': ('start_date',)},
        ),
        migrations.AlterModelOptions(
            name='constructormultiplier',
            options={'ordering': ('championship', 'constructor')},
        ),
        migrations.AlterModelOptions(
            name='dnaentry',
            options={'ordering': ('race',)},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('championship', 'championship_order')},
        ),
        migrations.AlterModelOptions(
            name='raceentry',
            options={'ordering': ('race', 'finish_position')},
        ),
        migrations.AlterModelOptions(
            name='rulechapter',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='ruleentry',
            options={'ordering': ('chapter', 'number')},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('location',)},
        ),
        migrations.RemoveConstraint(
            model_name='race',
            name='race_unique_championship_order',
        ),
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_unique_driver_race',
        ),
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_dna_notnull',
        ),
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_unique_driver_qualifying_position',
        ),
        migrations.RemoveConstraint(
            model_name='raceentry',
            name='raceentry_unique_driver_finish_position',
        ),
        migrations.AddField(
            model_name='race',
            name='driver_of_the_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='driver_of_the_day_set', to='leaderboard.driver'),
        ),
    ]
