# Generated by Django 4.0 on 2022-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0032_alter_championship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Driver Number'),
        ),
    ]
