# Generated by Django 4.0 on 2022-01-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0033_driver_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='drivers',
        ),
    ]
