# Generated by Django 4.0 on 2022-01-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0034_remove_championship_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='drivers',
            field=models.ManyToManyField(blank=True, through='leaderboard.ChampionshipDriver', to='leaderboard.Driver'),
        ),
        migrations.AddField(
            model_name='championshipdriver',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.championship'),
        ),
        migrations.AddField(
            model_name='championshipdriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.driver'),
        ),
        migrations.AddField(
            model_name='championshipdriver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leaderboard.team'),
        ),
    ]
