# Generated by Django 4.0 on 2022-01-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0035_championshipdriver_championship_drivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championshipdriver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='leaderboard.team'),
        ),
    ]
