# Generated by Django 4.0 on 2022-02-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0037_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'get_latest_by': 'start_date', 'ordering': ('-start_date',)},
        ),
    ]
