# Generated by Django 4.0.2 on 2022-02-06 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0038_alter_championship_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='overtakes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Overtakes'),
        ),
    ]
