# Generated by Django 4.0.2 on 2022-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0039_raceentry_overtakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipdriver',
            name='penalty_points',
            field=models.IntegerField(default=0, verbose_name='Penalty Points'),
        ),
        migrations.AddField(
            model_name='constructormultiplier',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constructormultiplier',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
    ]
