# Generated by Django 4.0.2 on 2022-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0041_remove_raceentry_pit_stops_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='raceentry_unique_driver_race'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'qualifying_position'), name='raceentry_unique_driver_qualifying_position'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'finish_position'), name='raceentry_unique_driver_finish_position'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bot', True), ('driver__isnull', True), ('team__isnull', True)), models.Q(('bot', False), ('driver__isnull', False)), _connector='OR'), name='raceentry_dna_notnull'),
        ),
    ]
